sudo: false
language: python
python:
- 3.4
- 3.5
- 3.6
env:
- BUILD=py
matrix:
  include:
  - python: 3.6
    env: BUILD=style
  - python: 3.6
    env: BUILD=docs
  - python: 3.6
    env: BUILD=mypy
  - python: 3.6
    env: BUILD=pytz201610
  - python: 3.6
    env: BUILD=pytz201702
  - python: 3.6
    env: BUILD=pytz_latest
  - python: 3.6
    env: BUILD=dateutil26
  - python: 3.6
    env: BUILD=dateutil_latest
  - python: 3.7
    dist: xenial
    sudo: true
addons:
  apt:
    packages:
    - language-pack-de
install:
- pip install tox
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
